import type { Scene } from '@graphlearning/flow'

// §6 codegen — the before/after is the whole section, and it is a CODE card because the thing that
// changed is literally code. The generated snippet is simplified but honest in shape: one while loop
// over rows with the filter and the projection inlined into it, which is exactly what Spark emits.
//
// The number worth carrying is in the top band: three operators used to mean three virtual calls per
// row, and a virtual call that does almost nothing is almost all overhead. Fusing them removes the
// calls AND keeps the row in CPU registers across all three steps — which is the half of the win
// people never hear about.
export const codegen: Scene = {
  id: 'codegen',
  padding: 0.11,
  flow: 'TB',
  nodes: [
    {
      id: 'before',
      label: 'Without codegen — three operators, three virtual calls PER ROW',
      pattern: 'group',
      icon: 'none',
      cols: 3,
      children: [
        { id: 'b-scan', label: 'Scan', variant: 'tile', pattern: 'storage', icon: 'database', sub: 'next() per row' },
        { id: 'b-filter', label: 'Filter', variant: 'tile', pattern: 'network', icon: 'funnel', sub: 'next() per row' },
        { id: 'b-project', label: 'Project', variant: 'tile', pattern: 'network', icon: 'braces', sub: 'next() per row' },
      ],
    },
    {
      id: 'after',
      kind: 'code',
      hug: true,
      filename: 'generated by Spark, compiled at runtime',
      label: [
        'while (scan.hasNext()) {',
        '    InternalRow row = scan.next();',
        '    if (row.getDecimal(2) <= 100) continue;   // the filter',
        '    out.write(row.getUTF8String(1));          // the project',
        '}',
      ].join('\n'),
    },
    { id: 'win', label: 'One loop, no calls', pattern: 'service', icon: 'zap', sub: 'and the row stays in registers' },
  ],
  edges: [
    { source: 'before', target: 'after', label: 'whole-stage codegen fuses every operator between two shuffles into ONE function' },
    { source: 'after', target: 'win', label: 'the `*(1)` and `*(2)` markers in a physical plan are the fused stages' },
  ],
}
